from __future__ import annotations

import hashlib
import os
import re
import subprocess
from pathlib import Path
from typing import Iterable

from .config import BINARY_EXTENSIONS, LOCK_FILE_NAMES, SKIP_DIRS, SUPPORTED_EXTENSIONS

TOKEN_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*|[./\-\w]+")


def normalize_repo_path(repo_path: str | Path) -> Path:
    return Path(repo_path).expanduser().resolve()


def repo_hash(repo_path: str | Path) -> str:
    path = str(normalize_repo_path(repo_path))
    return hashlib.sha256(path.encode("utf-8")).hexdigest()[:16]


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def estimate_tokens(text: str) -> int:
    if not text:
        return 0
    # Good enough for budget packing without adding a tokenizer dependency.
    words = len(re.findall(r"\S+", text))
    chars = len(text)
    return max(1, int(max(words * 1.35, chars / 4.0)))


def language_for_path(path: str | Path) -> str | None:
    p = Path(path)
    if p.name in {"Dockerfile", "Makefile"}:
        return "config"
    return SUPPORTED_EXTENSIONS.get(p.suffix.lower())


def is_lock_file(path: str | Path) -> bool:
    return Path(path).name in LOCK_FILE_NAMES


def is_probably_binary(path: Path, max_probe: int = 4096) -> bool:
    if path.suffix.lower() in BINARY_EXTENSIONS:
        return True
    try:
        data = path.read_bytes()[:max_probe]
    except OSError:
        return True
    return b"\x00" in data


def has_skipped_part(path: str | Path) -> bool:
    return any(part in SKIP_DIRS for part in Path(path).parts)


def is_generated_text(text: str, path: str | Path = "") -> bool:
    header_lines = text.splitlines()[:60]
    p = str(path).lower()
    generated_markers = [
        "auto-generated",
        "autogenerated",
        "generated by",
        "do not edit",
        "@generated",
    ]
    for line in header_lines:
        stripped = line.strip().lower()
        if not stripped.startswith(("#", "//", "/*", "*", "<!--", "--", "%", ";")):
            continue
        if any(marker in stripped for marker in generated_markers):
            return True
    return p.endswith((".min.js", ".bundle.js", ".pb.go", "_pb2.py"))


def run_git(repo_path: Path, args: list[str], check: bool = False) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(repo_path), *args],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=check,
    )


def is_git_repo(repo_path: Path) -> bool:
    proc = run_git(repo_path, ["rev-parse", "--is-inside-work-tree"])
    return proc.returncode == 0 and proc.stdout.strip() == "true"


def git_tracked_files(repo_path: Path) -> list[str]:
    proc = run_git(repo_path, ["ls-files"])
    if proc.returncode != 0:
        return []
    return [line for line in proc.stdout.splitlines() if line.strip()]


def walk_supported_files(repo_path: Path) -> list[str]:
    files: list[str] = []
    for root, dirs, names in os.walk(repo_path):
        root_path = Path(root)
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for name in names:
            full = root_path / name
            rel = full.relative_to(repo_path).as_posix()
            if language_for_path(rel) and not has_skipped_part(rel):
                files.append(rel)
    return files


def git_changed_files(repo_path: Path) -> set[str]:
    proc = run_git(repo_path, ["status", "--short"])
    if proc.returncode != 0:
        return set()
    changed: set[str] = set()
    for line in proc.stdout.splitlines():
        if not line.strip():
            continue
        item = line[3:].strip()
        if " -> " in item:
            item = item.split(" -> ", 1)[1]
        if item:
            changed.add(item)
    return changed


def git_recent_files(repo_path: Path, limit: int = 200) -> set[str]:
    proc = run_git(repo_path, ["log", "--name-only", "--pretty=format:", f"-n{limit}"])
    if proc.returncode != 0:
        return set()
    return {line.strip() for line in proc.stdout.splitlines() if line.strip()}


def tokenize(text: str) -> set[str]:
    return {tok.lower() for tok in TOKEN_RE.findall(text) if len(tok) > 1}


def safe_read_text(path: Path, max_bytes: int = 1_500_000) -> str | None:
    try:
        if path.stat().st_size > max_bytes:
            return None
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None


def common_path_suffix_match(a: str, b: str) -> bool:
    ap = Path(a).parts
    bp = Path(b).parts
    if not ap or not bp:
        return False
    max_len = min(len(ap), len(bp))
    for n in range(1, max_len + 1):
        if ap[-n:] == bp[-n:]:
            return True
    return False


def dedupe_preserve_order(values: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for value in values:
        if value not in seen:
            out.append(value)
            seen.add(value)
    return out
